version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "8000:80"
        depends_on:
            - database
        networks:
            - beeline
        command: sh -c "composer install && php artisan migrate --force && php -S 0.0.0.0:80 -t public"

    database:
        image: mysql:8
        container_name: laravel_mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tengrinews
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - beeline

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: database
            PMA_USER: user
            PMA_PASSWORD: password
        ports:
            - "8080:80"
        depends_on:
            - database
        networks:
            - beeline

networks:
    beeline:

volumes:
    mysql_data:
